{\rtf1\ansi\ansicpg1252\cocoartf1671\cocoasubrtf400
{\fonttbl\f0\fmodern\fcharset0 Courier;}
{\colortbl;\red255\green255\blue255;\red46\green95\blue225;\red245\green245\blue245;\red42\green55\blue62;
}
{\*\expandedcolortbl;;\cssrgb\c23137\c47059\c90588;\cssrgb\c96863\c96863\c96863;\cssrgb\c21569\c27843\c30980;
}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\sl280\partightenfactor0

\f0\fs28 \cf2 \cb3 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 runtime: \cf4 \strokec4 custom\cb1 \
\cf2 \cb3 \strokec2 env: \cf4 \strokec4 flex\
}